# -*- coding: utf-8 -*-
"""es.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hu84g4l_DJqSIse8XwUqS5UCiWp2t_ru
"""

def fe():
  print("hey")

